language: php

php:
  - 5.3
  - 5.4
  - 5.5

addons:
  firefox: "17.0"

before_script:
  - npm install java
  
script: 
  - phpunit --configuration phpunit.xml
  - java -jar Runnable_Selenium_Tests.jar
