<?php

use PROJ\Helper\XssHelper;

$em = \PROJ\Helper\DoctrineHelper::instance()->getEntityManager();
$user = $em->getRepository('\PROJ\Entities\Account')->find($_SESSION['userID'])->getStudent();
?>

<div id="management_right">
    <div id="management_container">
        <form name='management_account' method='post' enctype="multipart/form-data">
            <div style="width:96%; margin: 2%; overflow: auto;">
                <?php if (isset($additionalValues['error'])): ?>
                <div class="alert" style="margin-bottom:20px; padding: 5px;">
                     <p><?php echo $additionalValues['error']; ?></p>
                </div>
                <div style="clear:both;"></div>
                <?php
                endif;
                ?>
                <div class="left_container">
                    <p>Old Password: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="old_password" type="password" style="margin-top: 10px;" required autofocus />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>New Password: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="new_password" type="password" style="margin-top: 10px;" required />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>Repeat New Password: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="rep_new_password" type="password" style="margin-top: 10px;" required />
                </div>
                <div style="clear:both;"></div>
                <p style="margin-top:25px; font-size:10px; color: #a1a1a1;">Fields marked with asterisk (*) are required.</p>
            </div>
            <div style="width:100%; position: absolute; bottom: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div id="management_container_bottom">
                <div class="fancy_button" id="management_save" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Save</p>
                    <img src="/images/btn_right.png" />
                </div>
                <div class="fancy_button" id="management_cancel" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Cancel</p>
                    <img src="/images/btn_right.png" />
                </div>
                <div>
                </div>
            </div>
        </form>
    </div>
</div>