<div id="management_right">
    <div id="management_container">
        <form name='create_user' method='post' enctype="multipart/form-data">
            <div id="management_container_top">
                <div class="management_tab">
                    <a href="/Management/Users/">Manage Users</a>
                </div>
                <div class="spacerbar" style="float:left; height:37px;"></div>
                <div class="management_tab">
                    <a href="/Management/CreateUser/">Create Access Codes</a>
                </div>
            </div>
            <div style="width:100%; position: absolute; top: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div style="width:96%; margin: 2%; overflow: auto; margin-top:80px;" id="scrollable">
                <?php if (isset($additionalValues['error'])): ?>
                    <div class="alert" style="margin-bottom:20px; padding: 5px;">
                        <p><?php echo $additionalValues['error']; ?></p>
                    </div>
                    <div style="clear:both;"></div>
                    <?php
                endif;
                ?>
                <div class="left_container">
                    <p>E-Mail: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="email" type="text" value="<?php echo(isset($_POST['email']) ? $_POST['email'] : ''); ?>" style="margin-top: 10px;" required autofocus />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>Repeat E-Mail: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="rep_email" type="text" value="<?php echo(isset($_POST['rep_email']) ? $_POST['rep_email'] : ''); ?>" style="margin-top: 10px;" required />
                </div>
                <div style="clear:both;"></div>
                <p style="margin-top:25px; font-size:10px; color: #a1a1a1;">Fields marked with asterisk (*) are required.</p>
            </div>
            <div style="width:100%; position: absolute; bottom: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div id="management_container_bottom">
                <div class="fancy_button" id="create_user_save" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Create Access Code</p>
                    <img src="/images/btn_right.png" />
                </div>
        </form>
    </div>
</div>