<div id="management_right">
    <div id="management_container">
        <!-- Content goes here -->
        <div style="width:100%; position: absolute; bottom: 50px; height:1px; background-color: #dde0e8;">
        </div>
        <div id="management_container_bottom">
            <div class="fancy_button" id="login_button" style="left: 335px; top: 160px;">
                <img src="/images/btn_left.png" />
                <p>Save</p>
                <img src="/images/btn_right.png" />
            </div>
            <div class="fancy_button" id="login_button" style="left: 335px; top: 160px;">
                <img src="/images/btn_left.png" />
                <p>Cancel</p>
                <img src="/images/btn_right.png" />
            </div>
        <div>
    </div>
</div>