<?php

use PROJ\Helper\XssHelper;

$em = \PROJ\Helper\DoctrineHelper::instance()->getEntityManager();
$user = $em->getRepository('\PROJ\Entities\Account')->find($_SESSION['userID'])->getStudent();
?>

<div id="management_right">
    <div id="management_container">
        <form name='management_account' method='post' enctype="multipart/form-data">
            <div style="width:96%; margin: 2%; overflow: auto;">
                
            </div>
            <div style="width:100%; position: absolute; bottom: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div id="management_container_bottom">
                <div class="fancy_button" id="management_save" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Save</p>
                    <img src="/images/btn_right.png" />
                </div>
                <div class="fancy_button" id="management_cancel" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Cancel</p>
                    <img src="/images/btn_right.png" />
                </div>
                <div>
                </div>
            </div>
        </form>
    </div>
</div>