<?php

use PROJ\Helper\XssHelper;

$em = \PROJ\Helper\DoctrineHelper::instance()->getEntityManager();
$user = $em->getRepository('\PROJ\Entities\Account')->find($_SESSION['userID'])->getStudent();
?>

<div id="management_right">
    <div id="management_container">
        <form name='management_account' method='post' enctype="multipart/form-data">
            <div style="width:96%; margin: 2%; overflow: auto;">
                <?php if (isset($additionalValues['error'])): ?>
                <div class="alert" style="margin-bottom:20px; padding: 5px;">
                     <p><?php echo $additionalValues['error']; ?></p>
                </div>
                <div style="clear:both;"></div>
                <?php
                endif;
                ?>
                <div class="left_container">
                    <p>Voornaam: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="firstname" value="<?php echo($user->getFirstname()); ?>" type="text" style="margin-top: 10px;" maxlength="50" disabled />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>Achternaam: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="surname" value="<?php echo($user->getSurname()); ?>" type="text" style="margin-top: 10px;" maxlength="50" disabled />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>Country: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="country" required autofocus>
                        <option value="">-- Select a country --</option>
                        <?php
                        foreach($em->getRepository('\PROJ\Entities\Country')->findAll() as $res) {
                            echo('<option value="'.$res->getId().'"'.(isset($_POST['country']) ? ($_POST['country'] == $res->getId() ? ' selected' : '') : ($user->getCountry() == $res->getId() ? ' selected' : '')).'>'.$res->getName().'</option>');
                        };
                        ?>
                    </select>
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>City: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="city" value="<?php echo(isset($_POST['city']) ? XssHelper::sanitizeInput($_POST['city']) : $user->getCity()); ?>" type="text" style="margin-top: 10px;" required />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>Postal Code: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="zipcode" value="<?php echo(isset($_POST['zipcode']) ? XssHelper::sanitizeInput($_POST['zipcode']) : $user->getZipcode()); ?>" type="text" style="margin-top: 10px;" maxlength="6" required />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>Street: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="street" value="<?php echo(isset($_POST['street']) ? XssHelper::sanitizeInput($_POST['street']) : $user->getStreet()); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>House number: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="housenumber" value="<?php echo(isset($_POST['housenumber']) ? XssHelper::sanitizeInput($_POST['housenumber']) : $user->getHousenumber()); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>Addition:</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="addition" value="<?php echo(isset($_POST['addition']) ? XssHelper::sanitizeInput($_POST['addition']) : $user->getAddition()); ?>" type="text" style="margin-top: 10px;" maxlength="3" />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p>E-Mail: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="email" value="<?php echo(isset($_POST['email']) ? XssHelper::sanitizeInput($_POST['email']) : $user->getEmail()); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                </div>
                <div style="clear:both;"></div>
                <p style="margin-top:25px; font-size:10px; color: #a1a1a1;">Fields marked with asterisk (*) are required.</p>
            </div>
            <div style="width:100%; position: absolute; bottom: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div id="management_container_bottom">
                <div class="fancy_button" id="management_save" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Save</p>
                    <img src="/images/btn_right.png" />
                </div>
                <div class="fancy_button" id="management_cancel" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Cancel</p>
                    <img src="/images/btn_right.png" />
                </div>
                <div>
                </div>
            </div>
        </form>
    </div>
</div>