<div id="management_right">
    <div id="management_container">
        <form name='management_account' method='post' enctype="multipart/form-data">
            <div id="management_container_top">
                <div class="management_tab">
                    <a href="/Management/MyReviews/">My Reviews</a>
                </div>
                <div class="spacerbar" style="float:left; height:37px;"></div>
                <div class="management_tab">
                    <a href="/Management/MyLocations/">My Locations</a>
                </div>
            </div>
            <div style="width:100%; position: absolute; top: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div style="width:96%; margin: 2%; overflow: auto; margin-top:50px;" id="scrollable">
                <table class="ManagementTable">
                    <tr>
                        <th>Location:</th>
                        <th>Type:</th>
                        <th>Status:</th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <td colspan="4"><p>No locations found</p>
                    </tr>
                </table>
            </div>
            <div style="width:100%; position: absolute; bottom: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div id="management_container_bottom">
                <div class="fancy_button" id="mylocation_add" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Create New Location</p>
                    <img src="/images/btn_right.png" />
                </div>
        </form>
    </div>
</div>