<div id="management_right">
    <div id="management_container">
        <form name='management_account' method='post' enctype="multipart/form-data">
            <div id="management_container_top">
                <div class="management_tab">
                    <a href="/Management/MyReviews/">My Reviews</a>
                </div>
                <div class="spacerbar" style="float:left; height:37px;"></div>
                <div class="management_tab">
                    <a href="/Management/MyProjects/">My Projects</a>
                </div>
                <div class="spacerbar" style="float:left; height:37px;"></div>
                <div class="management_tab">
                    <a href="/Management/MyLocations/">My Locations</a>
                </div>
            </div>
            <div style="width:100%; position: absolute; top: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div style="width:96%; margin: 2%; overflow: auto; margin-top:50px;" id="scrollable">
                <table class="ManagementTable">
                    <tr>
                        <th>Type:</th>
                        <th>Location:</th>
                        <th>Start Date:</th>
                        <th>End Date:</th>
                        <th colspan="3">Status:</th>
                    </tr>
                    <?php
                    $em = \PROJ\Helper\DoctrineHelper::instance()->getEntityManager();
                    $user = $em->getRepository('\PROJ\Entities\Account')->find($_SESSION['userID']);
                    $qb = $em->createQueryBuilder();
                    $qb->select('i')
                            ->from('\PROJ\Entities\Project', 'i')
                            ->where($qb->expr()->eq('i.student', $qb->expr()->literal($user->getStudent()->getId())))
                            ->orderBy('i.type', 'ASC');
                    $res = $qb->getQuery()->getResult();
                    foreach ($res as $r) {
                        ?>
                        <tr>
                            <td><p><?php echo ucfirst($r->getType()); ?></p></td>
                            <td><p><?php echo $r->getInstitute()->getName(); ?> (<?php echo $r->getInstitute()->getPlace(); ?>)</p></td>
                            <td><p><?php echo $r->getStartDate()->format('F Y'); ?></p></td>
                            <td><p><?php echo $r->getendDate()->format('F Y'); ?></p></td>
                            <td><p><?php echo ucfirst($r->getAcceptanceStatus()); ?></p></td>
                            <?php
                            if ($r->getAcceptanceStatus() == "pending") {
                                ?>
                                <td style="width: 40px;"><img class="action_btn myprojects_update" data-project-id="<?php echo $r->getId(); ?>" src="/images/edit.png" /></td>
                                <td style="width: 40px;"><img class="action_btn myprojects_remove" data-project-id="<?php echo $r->getId(); ?>" src="/images/delete.png" /></td>
                                <?php
                            }
                            ?>
                        </tr>
                        <?php
                    }

                    if (count($res) == 0) {
                        ?>
                        <tr>
                            <td colspan="5"><p>No projects found</p></td>
                        </tr>
                        <?php
                    }
                    ?>
                </table>
            </div>
            <div style="width:100%; position: absolute; bottom: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div id="management_container_bottom">
                <div class="fancy_button myprojects_add" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Create Project</p>
                    <img src="/images/btn_right.png" />
                </div>
        </form>
    </div>
</div>