<div id="management_right">
    <div id="management_container">
        <form name='management_account' method='post' enctype="multipart/form-data">
            <div id="management_container_top">
                <div class="management_tab">
                    <a href="/Management/MyReviews/">My Reviews</a>
                </div>
                <div class="spacerbar" style="float:left; height:37px;"></div>
                <div class="management_tab">
                    <a href="/Management/MyLocations/">My Locations</a>
                </div>
            </div>
            <div style="width:100%; position: absolute; top: 50px; height:1px; background-color: #dde0e8;">
            </div>
            <div style="width:96%; margin: 2%; overflow: auto; margin-top:50px;">
                <table>
                    <tr>
                        <td></td>
                    </tr>
                </table>
        </form>
    </div>
</div>