<?php

use PROJ\Helper\XssHelper;

$em = \PROJ\Helper\DoctrineHelper::instance()->getEntityManager();
$user = $em->getRepository('\PROJ\Entities\Account')->find($_SESSION['userID'])->getStudent();
?>

<div id="management_right">
    <div id="management_container">

        <div style="width:100%; position: absolute; bottom: 50px; height:1px; background-color: #dde0e8;">
        </div>
        <form name='upload' action="uploadFile" method='post' enctype="multipart/form-data">


            <input type="file" name="file" id="file"><br>


            <div id="management_container_bottom">
                <div class="fancy_button" id="file_upload">
                    <img src="/images/btn_left.png" />
                    <p>Upload Excelsheet</p>
                    <img src="/images/btn_right.png" /></div>
            </div>
        </form>
    </div>
</div>