<?php

use PROJ\Helper\RightHelper;
?>
<div id="management_right">
    <div id="management_container">
        <form name='with_selected_form' method='post' enctype="multipart/form-data">
            <div style="width:96%; margin: 2%; overflow: auto;" id="scrollable">
                <table class="ManagementTable">
                    <tr>
                        <th><input type="checkbox" id="checkall" style="width:auto; margin-top:3px;"></th>
                        <th>Location:</th>
                        <th>Type:</th>
                        <th>Overall score:</th>
                        <th>Owner:</th>
                        <th>Status:</th>
                        <th colspan="2"></th>
                    </tr>
                    <?php
                    $em = \PROJ\Helper\DoctrineHelper::instance()->getEntityManager();
                    $qb = $em->createQueryBuilder();
                    $qb->select('rev, proj, inst, stud')
                            ->from('\PROJ\Entities\Review', 'rev')
                            ->leftjoin('rev.project', 'proj')
                            ->leftjoin('proj.institute', 'inst')
                            ->leftjoin('proj.student', 'stud')
                            ->orderBy('inst.name', 'ASC');
                    $reviews = $qb->getQuery()->getResult();

                    foreach ($reviews as $review) {
                        //Count number of Projects for student
                        /*
                          $qb = $em->createQueryBuilder();
                          $qb->select('p')
                          ->from('\PROJ\Entities\Project', 'p')
                          ->join('p.review', 'r')
                          ->where($qb->expr()->eq('p.student', $qb->expr()->literal($student->getId())));
                          $reviews = $qb->getQuery()->getResult(); */
                        ?>
                        <tr>
                            <td><input type="checkbox" name="selection[]" value="<?php echo $review->getId(); ?>" style="width:auto; margin-top:3px;"></td>
                            <td><p><?php echo $review->getProject()->getInstitute()->getName() . ' (' . $review->getProject()->getInstitute()->getPlace() . ')'; ?></p></td>
                            <td><p><?php echo ucfirst($review->getProject()->getType()); ?></p></td>
                            <td><p><?php echo $review->getRating(); ?></p></td>
                            <td><p><?php echo ucfirst($review->getProject()->getStudent()->getFullName()); ?></p></td>
                            <td><p><?php echo ucfirst($review->getAcceptanceStatus()); ?></p></td>
                            <td style="width: 40px;"><img class="action_btn myreview_update" data-review-id="<?php echo $review->getId(); ?>" src="/images/edit.png" /></td>
                            <td style="width: 40px;"><img class="action_btn myreview_remove" data-review-id="<?php echo $review->getId(); ?>" src="/images/delete.png" /></td>
                        </tr>
                        <?php
                    }
                    if (count($reviews) == 0) {
                        ?>
                        <tr>
                            <td colspan="7"><p>No Locations found</p></td>
                        </tr>
                        <?php
                    }
                    ?>
                </table>
                <img src="/images/arrow_ltr.png">
                <select style="width:auto; height:auto; padding: 3px;" id="apply_to_all" data-page="Review">
                    <option>With Selected:</option>
                    <?php if (RightHelper::loggedUserHasRight("UPDATE_REVIEW")) { ?>
                        <optgroup label="Status">
                            <option value="status_declined">Set to Declined</option>
                            <option value="status_pending">Set to Pending</option>
                            <option value="status_approved">Set to Approved</option>
                        </optgroup>
                    <?php } ?>
                    <?php if (RightHelper::loggedUserHasRight("DELETE_REVIEW")) { ?>
                        <optgroup label="Other">
                            <option value="remove">Remove</option>
                        </optgroup>
                    <?php } ?>
                </select>
            </div>
        </form>
    </div>