<?php
$ac = new PROJ\Services\AccountService();
?>
<header class="shadow">
    <nav>
        <button class="headerbutton" onclick=location.href="/" style="float:left;">Kaart</button>
        <?php if($ac->isLoggedIn()): ?>
        <button class="headerbutton" onclick=location.href="/Account/Logout">Log uit</button>
        <button class="headerbutton" >Welkom <?php echo sprintf("%s", $_SESSION['user']->getStudent()->getFirstname()); ?></button>
        <?php else: ?>
        <button class="headerbutton" onclick=location.href="/Account/Login">Log in</button>
        <button class="headerbutton" onclick=location.href="/account/Register">Registreren</button>
        <?php if(isset($search)) { ?>
        <input id="searchbar" type="text" placeholder="Search">
        <?php } ?>
        <?php endif; ?>
    </nav>
</header>