<?php
$ac = new PROJ\Services\AccountService();
?>
<header class="shadow">
    <nav>
        <button class="headerbutton" onclick=location.href="/" style="float:left;">Kaart</button>
        <?php if($ac->isLoggedIn()): ?>
        <button class="headerbutton" onclick=location.href="/Account/Logout">Log uit</button>
        <button class="headerbutton" >Welkom <?php echo sprintf("%s", $_SESSION['user']->getStudent()->getFirstname()); ?></button>
        <?php else: ?>
        <button class="headerbutton" onclick=location.href="/Account/Login">Log in</button>
        <button class="headerbutton" onclick=location.href="/account/Register">Registreren</button>
        <?php endif; ?>
        <?php if(isset($search)) { ?>
        <div style="float:right; width:15px;">&nbsp;</div>
        <div style="float:right; position: relative; margin: 3px 5px 3px 0px;">
            <input id="searchbar" type="text" placeholder="Search">
            <div id="searchresult">
                
            </div>
        </div>
        <?php } ?>
    </nav>
</header>