<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
<script type="text/javascript" src="http://eightmedia.github.io/hammer.js/dist/jquery.hammer.js"></script>
<script type="text/javascript" src="/tal/js/flowtype.js"></script>
<script type="text/javascript" src="/tal/js/json2html.js"></script>
<script type="text/javascript" src="/tal/js/jquery.json2html.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        var map; /* Main map variable */
        var iconBase = '/tal/images/';
        var icons = {
            university: {
                icon: iconBase + 'university.png'
            },
            business: {
                icon: iconBase + 'business.png'
            }
        };
        $('aside').flowtype({
            minimum: 500,
            maximum: 1200,
            fontRatio: 50
        });
        function openSidebar() {
            $("aside").removeClass('closed');
        }

        function closeSidebar() {
            $("aside").addClass('closed');
        }

        function toggleSidebar() {
            if (!$('aside').hasClass('closed')) {
                closeSidebar();
            } else {
                openSidebar();
            }
        }

        $('aside').hammer().on('dragright', function(e) {
            e.preventDefault();
            openSidebar();
        });
        $('aside').on('dragleft', function(e) {
            if (!$('aside').hasClass('closed')) {
                e.preventDefault();
                closeSidebar();
            }
        });
        $('#swipeline').on('click', function(e) {
            e.stopPropagation();
            e.preventDefault();
            toggleSidebar();
        });
        
        function loadJsonMarkers() {
            $.getJSON('/tal/ajax/allLocations/', function(data) {
                $.each(data.locations, function(i, location) {
                    var marker = new google.maps.Marker({
                        position: new google.maps.LatLng(location.lat, location.lng),
                        map: map,
                        icon: icons[location.type].icon,
                        animation: google.maps.Animation.NONE,
                        title: location.title,
                        id: location.id
                    });
                    google.maps.event.addListener(marker, 'click', function() {
                        map.setZoom(13);
                        map.setCenter(marker.getPosition());
                        //TODO open sidebar with info
                        loadLocation();
                    });
                });
            });
        }

        function loadLocation() {
            var sidebar = $('aside');
            
            $.getJSON('/tal/ajax/locationReview/loc=1/', function(data) {
                sidebar.text("");
                sidebarHeader = $('<div class="row clearfix"/>');
                sidebarHeader.append("<h2 class=\"column full highlight\">" + data.name + "</h2>");
                sidebarHeader.append("<h3 class=\"column half italic\">" + data.place + "</h3>");
                sidebarHeader.append("<h3 class=\"column half\">" + data.type + "</h3>");
                sidebar.append(sidebarHeader);
                sidebarHeader.append("<p class=\"column half\">Door</h3>");
                sidebarHeader.append("<p class=\"column half\">Beoordeling</h3>");

                var row;
                for (var i = 0; i < data.reviews.length; i++) {
                    sidebar.append("<div class=\"row clearfix\"/><span class=\"column full\">" + data.reviews[i].reviewer.name + "</span></div>");
                    
                    row = $('<p class="row clearfix"/>');
                    row.append("<span class=\"column half italic\">" + data.reviews[i].type + "</span>");
                    var stars = $("<span class=\"column half\"/>");
                    for (var j = 0; j < 5; j++) { //5 max rating
                        if(data.reviews[i].rating > j){
                            stars.append("<span class=\"highlight\">&#10032;</span>");
                        } else {
                            stars.append("<span>&#10032;</span>");
                        }
                    }
                    row.append(stars);
                    sidebar.append(row);
                }
            });
        }

        //subtrackt the header size from the map canvas, removing the scrollbar
        function correctHeaderOffset() {
            var h = $(window).height();
            var headerHeight = $('header').height();
            //Force fill screen, strange bug with maps
            $('#map').css('height', h);
            $('aside').css('top', headerHeight);
            $('aside').css('height', h - headerHeight);
        }


        function initialize() {
            var avansStyle = (function() {
                var json = null;
                $.ajax({
                    'async': false,
                    'global': false,
                    'url': "/tal/js/mapStyle.json",
                    'dataType': "json",
                    'success': function(data) {
                        json = data;
                    }
                });
                return json;
            })();
            var mapOptions = {
                center: new google.maps.LatLng(-34.397, 150.644),
                zoom: 8,
                streetViewControl: false,
                zoomControl: false,
                panControl: false,
                mapTypeControl: false,
                styles: avansStyle
            };
            map = new google.maps.Map(document.getElementById("map"),
                    mapOptions);
            //Force absolute positioning after map tiles are loaded
            google.maps.event.addListener(map, 'tilesloaded', function() {
                document.getElementById('map').style.position = 'absolute';
            });
            //Correct the height of the map after resizing
            google.maps.event.addListener(map, 'resize', function() {
                var mainHeight = $('main').height();
                var headerHeight = $('header').height();
                $('#map').css('height', (mainHeight - headerHeight));
            });
            //Force a recalculation of the map height
            correctHeaderOffset();
            loadJsonMarkers();
        }

        google.maps.event.addDomListener(window, 'load', initialize);
        //Register the correctHeaderOffset callback on windows resizing.
        $(window).resize(correctHeaderOffset).resize();
    });



</script>
