<?php
$em = \PROJ\Helper\DoctrineHelper::instance()->getEntityManager();

use PROJ\Helper\RightHelper;

$toTranslate = array("enter_details", "type", "select_type", "education", "business", "fields_marked", 
    "project", "eps", "graduation", "internship", "minor", "first_name", "surname", "username", "email", "company_name", 
    "company_country", "select_country", "company_city", "company_street", "company_house_number", "company_zip_code", 
    "company_email", "company_phone", "create_location", "please_review", "create_a_project", "select_project", 
    "assignment_score", "score", "not_relevant", "guidance_score", "accommodation_score", "overall_score", "review", 
    "add_project", "please_details", "select_location", "start_date", "year", "month", "end_date", "details_user", 
    "rml", "name", "location", "process_remove", "are_you_sure", "cancel", "remove", "rmr", "project", "rmp", 
    "remove_connected", "rmu", "remove_any", "confirm");
$translator = new PROJ\Services\TranslationService();
$translated = $translator->translateAll($toTranslate);
?>
<!-- Loading Icon -->
<img src="/images/loading.gif" class="fullscreen_loading_icon">

<!-- Create Location -->

<div id="blackout_create_location">
    <div id="register_container">
        <form name='create_location_form' method='post' enctype="multipart/form-data">
            <img src="/images/register_top.png">
            <div id="register_container_tophalf">
                <div class="alert" id="addLocationError" style="display:none; margin-bottom:20px; padding: 5px; clear:both;">
                    <p></p>
                </div>
                <p style="font-weight:bold; margin-bottom:15px;"><?php echo $translated['enter_details'] ?> :</p>
                    <div style="clear:both;"></div>s

                    <div class="left_container">
                        <p style="padding-top:18px;"><?php echo $translated['type'] ?>: *</p>
                    </div>
                    <div style="width:5%; float:left;">&nbsp;</div>
                    <div class="right_container">
                        <select name="type" required autofocus>
                            <option>-- <?php echo $translated['select_type'] ?> --</option>
                            <option value="education"><?php echo $translated['education'] ?></option>
                            <option value="business"><?php echo $translated['business'] ?></option>
                        </select>
                    </div>
                    <div style="clear:both;"></div>

                    <div class="left_container">
                        <p style="padding-top:18px;"><?php echo $translated['company_name'] ?>: *</p>
                    </div>
                    <div style="width:5%; float:left;">&nbsp;</div>
                    <div class="right_container">
                        <input name="name" value="" type="text" style="margin-top: 10px;" maxlength="50" />
                    </div>
                    <div style="clear:both;"></div>

                    <div class="left_container">
                        <p style="padding-top:18px;"><?php echo $translated['company_country'] ?>: *</p>
                    </div>
                    <div style="width:5%; float:left;">&nbsp;</div>
                    <div class="right_container">
                        <select name="country" required autofocus>
                            <option value="">-- <?php echo $translated['select_country'] ?> --</option>
                            <?php
                            foreach ($em->getRepository('\PROJ\Entities\Country')->findAll() as $res) {
                                echo('<option value="' . $res->getId() . '">' . $res->getName() . '</option>');
                            }
                            ?>
                        </select>
                    </div>
                    <div style="clear:both;"></div>

                    <div class="left_container">
                        <p style="padding-top:18px;"><?php echo $translated['enter_details'] ?>: *</p>
                    </div>
                    <div style="width:5%; float:left;">&nbsp;</div>
                    <div class="right_container">
                        <input name="city" value="" type="text" style="margin-top: 10px;" maxlength="50" />
                    </div>
                    <div style="clear:both;"></div>

                    <div class="left_container">
                        <p style="padding-top:18px;"><?php echo $translated['company_street'] ?>: *</p>
                    </div>
                    <div style="width:5%; float:left;">&nbsp;</div>
                    <div class="right_container">
                        <input name="street" value="" type="text" style="margin-top: 10px;" maxlength="50" />
                    </div>
                    <div style="clear:both;"></div>

                    <div class="left_container">
                        <p style="padding-top:18px;"><?php echo $translated['company_house_number'] ?>: *</p>
                    </div>
                    <div style="width:5%; float:left;">&nbsp;</div>
                    <div class="right_container">
                        <input name="housenumber" value="" type="text" style="margin-top: 10px;" maxlength="50" />
                    </div>
                    <div style="clear:both;"></div>

                    <div class="left_container">
                        <p style="padding-top:18px;"><?php echo $translated['company_zip_code'] ?>: *</p>
                    </div>
                    <div style="width:5%; float:left;">&nbsp;</div>
                    <div class="right_container">
                        <input name="postalcode" value="" type="text" style="margin-top: 10px;" maxlength="6" />
                    </div>
                    <div style="clear:both;"></div>

                    <div class="left_container">
                        <p style="padding-top:18px;"><?php echo $translated['company_email'] ?>: *</p>
                    </div>
                    <div style="width:5%; float:left;">&nbsp;</div>
                    <div class="right_container">
                        <input name="email" value="" type="text" style="margin-top: 10px;" />
                    </div>
                    <div style="clear:both;"></div>

                    <div class="left_container">
                        <p style="padding-top:18px;"><?php echo $translated['company_phone'] ?>:</p>
                    </div>
                    <div style="width:5%; float:left;">&nbsp;</div>
                    <div class="right_container">
                        <input name="telephone" value="" type="text" style="margin-top: 10px;" maxlength="50" />
                    </div>
                    <div style="clear:both;"></div>


                    <p style="margin-top:25px; font-size:10px; color: #a1a1a1;"><?php echo $translated['fields_marked'] ?></p>
            </div>
            <img src="/images/register_split.png">
            <div id="register_container_bottomhalf">
                <div class="fancy_button" id="location_action" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['create_location'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
            </div>
            <img src="/images/register_bottom.png">
        </form>
    </div>
</div>


<!-- Create Review -->

<div id="blackout_create_review">
    <div id="register_container" style="height: 750px; margin-top: -375px;">
        <form name='create_review_form' method='post' enctype="multipart/form-data">
            <img src="/images/register_top.png">
            <div id="register_container_tophalf">
                <div class="alert" id="addReviewError" style="display:none; margin-bottom:20px; padding: 5px; clear:both;">
                    <p></p>
                </div>
                <p style="font-weight:bold; margin-bottom:15px;"><?php echo $translated['please_review'] ?>:</p>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['project'] ?>: <a style="float:none; cursor: pointer; text-decoration: underline" class="myprojects_add">(<?php echo $translated['create_a_project'] ?>)</a>*</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="project" required>
                        <option value="">-- <?php echo $translated['select_project'] ?> --</option>
                        <?php
                        $user = $em->getRepository('\PROJ\Entities\Account')->find($_SESSION['userID']);
                        $qb = $em->createQueryBuilder();
                        $qb->select('p.id, i.name, i.place, p.type')
                                ->from('\PROJ\Entities\Project', 'p')
                                ->leftJoin('p.institute', 'i');
                        if (!RightHelper::loggedUserHasRight("VIEW_PROJECTS"))
                            $qb->where($qb->expr()->eq('p.student', $qb->expr()->literal($user->getStudent()->getId())));

                        $qb->orderBy('i.name', 'ASC');
                        $res = $qb->getQuery()->getResult();
                        foreach ($res as $r) {
                            echo('<option value="' . $r['id'] . '">' . $r['name'] . ' (' . $r['place'] . ') - ' . ucfirst($r['type']) . '</option>');
                        }
                        ?>
                    </select>
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['assignment_score'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="assignment_score" required>
                        <option value=""><?php echo $translated['score'] ?></option>
                        <option value="0"><?php echo $translated['not_relevant'] ?></option>
                        <?php
                        for ($i = 1; $i < 6; $i++) {
                            echo('<option value="' . $i . '">' . $i . '</option>');
                        }
                        ?>
                    </select>
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['guidance_score'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="guidance_score" required>
                        <option value=""><?php echo $translated['score'] ?></option>
                        <option value="0"><?php echo $translated['not_relevant'] ?></option>
                        <?php
                        for ($i = 1; $i < 6; $i++) {
                            echo('<option value="' . $i . '">' . $i . '</option>');
                        }
                        ?>
                    </select>
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['accommodation_score'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="accomodation_score" required>
                        <option value=""><?php echo $translated['score'] ?></option>
                        <option value="0"><?php echo $translated['not_relevant'] ?></option>
                        <?php
                        for ($i = 1; $i < 6; $i++) {
                            echo('<option value="' . $i . '">' . $i . '</option>');
                        }
                        ?>
                    </select>
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['overall_score'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="overall_score" required>
                        <option value=""><?php echo $translated['score'] ?></option>
                        <option value="0"><?php echo $translated['not_relevant'] ?></option>
                        <?php
                        for ($i = 1; $i < 6; $i++) {
                            echo('<option value="' . $i . '">' . $i . '</option>');
                        }
                        ?>
                    </select>
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['review'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <textarea name="review" required></textarea>
                </div>
                <div style="clear:both;"></div>


                <p style="margin-top:25px; font-size:10px; color: #a1a1a1;"><?php echo $translated['fields_marked'] ?></p>
            </div>
            <img src="/images/register_split.png">
            <div id="register_container_bottomhalf">
                <div class="fancy_button" id="review_action" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['add_project'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
            </div>
            <img src="/images/register_bottom.png">
        </form>
    </div>
</div>

<!-- Create Project -->

<div id="blackout_create_project">
    <div id="register_container" style="height: 390px; margin:0px; top:0px; left:0px;">
        <form name='create_project_form' method='post' enctype="multipart/form-data">
            <img src="/images/register_top.png">
            <div id="register_container_tophalf">
                <div class="alert" id="addProjectError" style="display:none; margin-bottom:20px; padding: 5px; clear:both;">
                    <p></p>
                </div>
                <p style="font-weight:bold; margin-bottom:15px;"><?php echo $translated['please_details'] ?> :</p>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['type'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="type" required autofocus>
                        <option value="">-- <?php echo $translated['select_type'] ?> --</option>
                        <option value="minor"><?php echo $translated['minor'] ?></option>
                        <option value="internship"><?php echo $translated['internship'] ?></option>
                        <option value="graduation"><?php echo $translated['graduation'] ?></option>
                        <option value="ESP"><?php echo $translated['eps'] ?></option>
                    </select>
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;">Location: <a style="float:none; cursor: pointer; text-decoration: underline" class="mylocation_add">(<?php echo $translated['create_location'] ?>)</a>*</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="location" required>
                        <option value="">-- <?php echo $translated['select_location'] ?> --</option>
                        <?php
                        $user = $em->getRepository('\PROJ\Entities\Account')->find($_SESSION['userID']);
                        $qb = $em->createQueryBuilder();
                        $qb->select('i')
                                ->from('\PROJ\Entities\Institute', 'i');

                        if (!RightHelper::loggedUserHasRight("VIEW_LOCATIONS")) {
                            $qb->where($qb->expr()->eq('i.creator', $qb->expr()->literal($user->getStudent()->getId())))
                                    ->orWhere($qb->expr()->eq('i.acceptanceStatus', $qb->expr()->literal('approved')));
                        }
                        $qb->orderBy('i.type', 'ASC');
                        $res = $qb->getQuery()->getResult();
                        foreach ($res as $r) {
                            echo('<option value="' . $r->getId() . '">' . $r->getName() . ' (' . $r->getPlace() . ')</option>');
                        }
                        ?>
                    </select>
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['start_date'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="start_year" style="width:45%" required>
                        <option value=""><?php echo $translated['year'] ?></option>
                        <?php
                        for ($i = date("Y"); $i > date("Y") - 10; $i--) {
                            echo('<option value="' . $i . '">' . $i . '</option>');
                        }
                        ?>
                    </select>
                    <select name="start_month" style="width:45%; margin-left:10%;" required>
                        <option value=""><?php echo $translated['month'] ?></option>
                        <?php
                        for ($i = 1; $i < 13; $i++) {
                            echo('<option value="' . $i . '">' . date('F', mktime(0, 0, 0, $i, 1, 2000)) . '</option>');
                        }
                        ?>
                    </select>
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['end_date'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <select name="end_year" style="width:45%" required>
                        <option value=""><?php echo $translated['year'] ?></option>
                        <?php
                        for ($i = date("Y"); $i > date("Y") - 10; $i--) {
                            echo('<option value="' . $i . '">' . $i . '</option>');
                        }
                        ?>
                    </select>
                    <select name="end_month" style="width:45%; margin-left:10%;" required>
                        <option value=""><?php echo $translated['month'] ?></option>
                        <?php
                        for ($i = 1; $i < 13; $i++) {
                            echo('<option value="' . $i . '">' . date('F', mktime(0, 0, 0, $i, 1, 2000)) . '</option>');
                        }
                        ?>
                    </select>
                </div>
                <div style="clear:both;"></div>


                <p style="margin-top:25px; font-size:10px; color: #a1a1a1;"><?php echo $translated['fields_marked'] ?></p>
            </div>
            <img src="/images/register_split.png">
            <div id="register_container_bottomhalf">
                <div class="fancy_button" id="projects_action" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Create Project</p>
                    <img src="/images/btn_right.png" />
                </div>
            </div>
            <img src="/images/register_bottom.png">
        </form>
    </div>
</div>

<!-- Update User -->

<div id="blackout_create_user">
    <div id="register_container">
        <form name='create_user_form' method='post' enctype="multipart/form-data">
            <img src="/images/register_top.png">
            <div id="register_container_tophalf">
                <div class="alert" id="addUserError" style="display:none; margin-bottom:20px; padding: 5px; clear:both;">
                    <p></p>
                </div>
                <p style="font-weight:bold; margin-bottom:15px;"><?php echo $translated['details_user'] ?>:</p>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['first_name'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="firstname" value="" type="text" style="margin-top: 10px;" maxlength="50" />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['surname'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="surname" value="" type="text" style="margin-top: 10px;" maxlength="50" />
                </div>
                <div style="clear:both;"></div>

                <div class="left_container">
                    <p style="padding-top:18px;"><?php echo $translated['username'] ?>: *</p>
                </div>
                <div style="width:5%; float:left;">&nbsp;</div>
                <div class="right_container">
                    <input name="username" value="" type="text" style="margin-top: 10px;" maxlength="50" />
                </div>
                <div style="clear:both;"></div>


                <p style="margin-top:25px; font-size:10px; color: #a1a1a1;"><?php echo $translated['fields_marked'] ?></p>
            </div>
            <img src="/images/register_split.png">
            <div id="register_container_bottomhalf">
                <div class="fancy_button" id="user_action" style="left: 335px; top: 160px;">
                    <img src="/images/btn_left.png" />
                    <p>Create User</p>
                    <img src="/images/btn_right.png" />
                </div>
            </div>
            <img src="/images/register_bottom.png">
        </form>
    </div>
</div>

<!-- remove Location -->

<div id="blackout_delete_location">
    <div id="register_container" style="height: 274px; left:auto; top: auto; margin: 0px;">
        <form name='create_location_form' method='post' enctype="multipart/form-data">
            <img src="/images/register_top.png">
            <div id="register_container_tophalf">
                <div class="alert" id="removeLocationError" style="display:none; margin-bottom:20px; padding: 5px; clear:both;">
                    <p></p>
                </div>
                <p style="margin-bottom:15px;"><?php echo $translated['rml'] ?>:</p>
                <div style="clear:both;"></div>
                <table>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['name'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveLocationName"><p></p></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['location'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveLocationLoc"><p></p></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['type'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveLocationType"><p></p></td>
                    </tr>
                </table>
                <div style="clear:both;"></div>
                <p style="margin:15px inherit;"><?php echo $translated['process_remove'] ?></p>
                <p style="margin:15px inherit;"><?php echo $translated['are_you_sure'] ?></p>
            </div>
            <img src="/images/register_split.png">
            <div id="register_container_bottomhalf">
                <div class="fancy_button blackout_cancel" style="margin-left:10px;">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['cancel'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
                <div class="fancy_button" id="remove_location">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['remove'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
            </div>
            <img src="/images/register_bottom.png">
        </form>
    </div>
</div>

<!-- remove Review -->

<div id="blackout_delete_review">
    <div id="register_container" style="height: 274px; left:auto; top: auto; margin: 0px;">
        <form name='create_review_form' method='post' enctype="multipart/form-data">
            <img src="/images/register_top.png">
            <div id="register_container_tophalf">
                <div class="alert" id="removeReviewError" style="display:none; margin-bottom:20px; padding: 5px; clear:both;">
                    <p></p>
                </div>
                <p style="margin-bottom:15px;"><?php echo $translated['rmr'] ?>:</p>
                <div style="clear:both;"></div>
                <table>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['project'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveProjectProject"><p></p></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['score'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveProjectScore"><p></p></td>
                    </tr>
                </table>
                <div style="clear:both;"></div>
                <p style="margin:15px inherit;"><?php echo $translated['are_you_sure'] ?></p>
            </div>
            <img src="/images/register_split.png">
            <div id="register_container_bottomhalf">
                <div class="fancy_button blackout_cancel" style="margin-left:10px;">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['cancel'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
                <div class="fancy_button" id="remove_review">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['remove'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
            </div>
            <img src="/images/register_bottom.png">
        </form>
    </div>
</div>

<!-- remove Project -->

<div id="blackout_delete_project">
    <div id="register_container" style="height: 274px; left:auto; top: auto; margin: 0px;">
        <form name='create_location_form' method='post' enctype="multipart/form-data">
            <img src="/images/register_top.png">
            <div id="register_container_tophalf">
                <div class="alert" id="removeProjectError" style="display:none; margin-bottom:20px; padding: 5px; clear:both;">
                    <p></p>
                </div>
                <p style="margin-bottom:15px;"><?php echo $translated['rmp'] ?>:</p>
                <div style="clear:both;"></div>
                <table>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['type'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveProjectType"><p></p></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['location'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveProjectnLoc"><p></p></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['start_date'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveProjectStartDate"><p></p></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['end_date'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveProjectEndDate"><p></p></td>
                    </tr>
                </table>
                <div style="clear:both;"></div>
                <p style="margin:15px inherit;"><?php echo $translated['remove_connected'] ?></p>
                <p style="margin:15px inherit;"><?php echo $translated['are_you_sure'] ?></p>
            </div>
            <img src="/images/register_split.png">
            <div id="register_container_bottomhalf">
                <div class="fancy_button blackout_cancel" style="margin-left:10px;">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['cancel'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
                <div class="fancy_button" id="remove_project">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['remove'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
            </div>
            <img src="/images/register_bottom.png">
        </form>
    </div>
</div>

<!-- remove User -->

<div id="blackout_delete_user">
    <div id="register_container" style="height: 274px; left:auto; top: auto; margin: 0px;">
        <form name='remove_user_form' method='post' enctype="multipart/form-data">
            <img src="/images/register_top.png">
            <div id="register_container_tophalf">
                <div class="alert" id="removeUserError" style="display:none; margin-bottom:20px; padding: 5px; clear:both;">
                    <p></p>
                </div>
                <p style="margin-bottom:15px;"><?php echo $translated['rmu'] ?>:</p>
                <div style="clear:both;"></div>
                <table>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['name'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveUserName"><p></p></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px 5px 5px 0px;"><p><?php echo $translated['email'] ?>:</p></td>
                        <td style="padding: 5px; font-weight: bold;" id="RemoveUserEmail"><p></p></td>
                    </tr>
                </table>
                <div style="clear:both;"></div>
                <p style="margin:15px inherit;"><?php echo $translated['remove_any'] ?></p>
                <p style="margin:15px inherit;"><?php echo $translated['are_you_sure'] ?></p>
            </div>
            <img src="/images/register_split.png">
            <div id="register_container_bottomhalf">
                <div class="fancy_button blackout_cancel" style="margin-left:10px;">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['cancel'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
                <div class="fancy_button" id="remove_user">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['remove'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
            </div>
            <img src="/images/register_bottom.png">
        </form>
    </div>
</div>

<!-- General Message -->

<div id="blackout_with_selected">
    <div id="register_container" style="height: 274px; left:auto; top: auto; margin: 0px;">
        <form name='remove_user_form' method='post' enctype="multipart/form-data">
            <img src="/images/register_top.png">
            <div id="register_container_tophalf">
                <div class="alert" id="removeUserError" style="display:none; margin-bottom:20px; padding: 5px; clear:both;">
                    <p></p>
                </div>
                <p id="with_selected_confirm_message"><!-- Script generated message --></p>
            </div>
            <img src="/images/register_split.png">
            <div id="register_container_bottomhalf">
                <div class="fancy_button blackout_cancel" style="margin-left:10px;">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['cancel'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
                <div class="fancy_button" id="with_selected_confirm">
                    <img src="/images/btn_left.png" />
                    <p><?php echo $translated['confirm'] ?></p>
                    <img src="/images/btn_right.png" />
                </div>
            </div>
            <img src="/images/register_bottom.png">
        </form>
    </div>
</div>