<?php

namespace PROJ\Proxies\__CG__\PROJ\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VoorbeeldEntitie2 extends \PROJ\Entities\VoorbeeldEntitie2 implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'id', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'name', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'INTwaarde', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'OneToOneRelation', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'ManyToOneRelation', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'ManyToManyRelation');
        }

        return array('__isInitialized__', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'id', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'name', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'INTwaarde', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'OneToOneRelation', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'ManyToOneRelation', '' . "\0" . 'PROJ\\Entities\\VoorbeeldEntitie2' . "\0" . 'ManyToManyRelation');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (VoorbeeldEntitie2 $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getManyToManyRelation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManyToManyRelation', array());

        return parent::getManyToManyRelation();
    }

    /**
     * {@inheritDoc}
     */
    public function setManyToManyRelation($ManyToManyRelation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManyToManyRelation', array($ManyToManyRelation));

        return parent::setManyToManyRelation($ManyToManyRelation);
    }

    /**
     * {@inheritDoc}
     */
    public function get_ManyToOneRelation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_ManyToOneRelation', array());

        return parent::get_ManyToOneRelation();
    }

    /**
     * {@inheritDoc}
     */
    public function set_ManyToOneRelation($ManyToOneRelation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'set_ManyToOneRelation', array($ManyToOneRelation));

        return parent::set_ManyToOneRelation($ManyToOneRelation);
    }

    /**
     * {@inheritDoc}
     */
    public function getOneToOneRelation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOneToOneRelation', array());

        return parent::getOneToOneRelation();
    }

    /**
     * {@inheritDoc}
     */
    public function setOneToOneRelation($OneToOneRelation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOneToOneRelation', array($OneToOneRelation));

        return parent::setOneToOneRelation($OneToOneRelation);
    }

    /**
     * {@inheritDoc}
     */
    public function getINTwaarde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getINTwaarde', array());

        return parent::getINTwaarde();
    }

    /**
     * {@inheritDoc}
     */
    public function setINTwaarde($INTwaarde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setINTwaarde', array($INTwaarde));

        return parent::setINTwaarde($INTwaarde);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

}
