<?php
use PROJ\Helper\XssHelper;
$header = new \PROJ\Tools\Template("Partial/Header");
$header->title = "Contact Formulier";

echo $header;

$bar = new \PROJ\Tools\Template("Partial/TopBar");
echo $bar;
?>
<div id="contact_container" style="height:140px; margin-top:-70px;">
    <form name='contact' method='post' enctype="multipart/form-data">
        <img src="/images/login_top.png">
        <div id="login_container_tophalf">
            <p>Your message was sent successfully.</p>
        </div>
        <img src="/images/login_split.png">
        <div id="login_container_bottomhalf">
            <div class="fancy_button" onclick="window.location='/';" style="left: 335px; top: 160px;">
                <img src="/images/btn_left.png" />
                <p>Back</p>
                <img src="/images/btn_right.png" />
            </div>
        </div>
        <img src="/images/login_bottom.png">
    </form>
</div>

<?php
$footer = new \PROJ\Tools\Template("Partial/Footer");
echo $footer;
?>