<?php

/*
 * 1 Worldmap
 * 2 Log uit
 * 3 welkom
 * 4 log in
 * 5 register
 * 6 location type
 * 7 education
 * 8 busines
 * 9 project type
 * 10 minor
 * 11 eps
 * 12 graduation
 * 13 internship
 * 14 country
 * 15 contact formulier
 * 16 to
 * 17 from
 * 18 subject
 * 19 message
 * 20 Fields marked with asterisk (*) are required.
 * 21 send
 * 22 Your message was sent successfully.
 * 23 back
 * 24 Login
 * 25 Username
 * 26 Password
 * 27 E-Mail
 * 28 First name
 * 29 Surname
 * 30 Zip code
 * 31 Street
 * 32 Street number
 * 33 Addition
 * 34 Registration code
 * 35 Register
 * 
 */

$toTranslate = array(24,25,26,24);
$translated = PROJ\Services\TranslationService::translateAll($toTranslate);

$header = new \PROJ\Tools\Template("Partial/Header");
$header->title = $translated[0];

echo $header;

$bar = new \PROJ\Tools\Template("Partial/TopBar");
echo $bar;
?>
<div id="login_container">
    <form name='login' method='post' enctype="multipart/form-data">
        <img src="/images/login_top.png">
        <div id="login_container_tophalf">
            <?php if (isset($error)): ?>
            <div class="alert" style="margin-bottom:20px; padding: 5px;">
                 <p><?php echo $error; ?></p>
            </div>
            <div style="clear:both;"></div>
            <?php
            endif;
            ?>
            <p><?php echo $translated[1] ?>:</p>
            <input type="text" value="" name="username" style="margin-top: 10px;" />
            <p style="margin-top:15px;"><?php echo $translated[2] ?>:</p>
            <input type="password" value="" name="password" style="margin-top: 10px;" />
        </div>
        <img src="/images/login_split.png">
        <div id="login_container_bottomhalf">
            <div class="fancy_button" id="login_button" style="left: 335px; top: 160px;">
                <img src="/images/btn_left.png" />
                <p><?php echo $translated[3] ?></p>
                <img src="/images/btn_right.png" />
            </div>
        </div>
        <img src="/images/login_bottom.png">
    </form>
</div>

<?php
$footer = new \PROJ\Tools\Template("Partial/Footer");
echo $footer;
?>