<?php

/*
 * 24 Login
 * 25 Username
 * 26 Password
 */

$toTranslate = array("login","username","password");
$translated = PROJ\Services\TranslationService::translateAll($toTranslate);

$header = new \PROJ\Tools\Template("Partial/Header");
$header->title = $translated["login"];

echo $header;

$bar = new \PROJ\Tools\Template("Partial/TopBar");
echo $bar;
?>
<div id="login_container">
    <form name='login' method='post' enctype="multipart/form-data">
        <img src="/images/login_top.png">
        <div id="login_container_tophalf">
            <?php if (isset($error)): ?>
            <div class="alert" style="margin-bottom:20px; padding: 5px;">
                 <p><?php echo $error; ?></p>
            </div>
            <div style="clear:both;"></div>
            <?php
            endif;
            ?>
            <p><?php echo $translated["username"] ?>:</p>
            <input type="text" value="" name="username" style="margin-top: 10px;" />
            <p style="margin-top:15px;"><?php echo $translated["[assword"] ?>:</p>
            <input type="password" value="" name="password" style="margin-top: 10px;" />
        </div>
        <img src="/images/login_split.png">
        <div id="login_container_bottomhalf">
            <div class="fancy_button" id="login_button" style="left: 335px; top: 160px;">
                <img src="/images/btn_left.png" />
                <p><?php echo $translated["login"] ?></p>
                <img src="/images/btn_right.png" />
            </div>
        </div>
        <img src="/images/login_bottom.png">
    </form>
</div>

<?php
$footer = new \PROJ\Tools\Template("Partial/Footer");
echo $footer;
?>