<?php
$header = new \PROJ\Tools\Template("Partial/Header");
$header->title = "User Management";

echo $header;

$bar = new \PROJ\Tools\Template("Partial/TopBar");
echo $bar;

$content = new \PROJ\Tools\Template("Management/".$page);
$content->additionalValues = $additionalValues;
?>
<div id="management_left">
    <h2>Management</h2>
    
    <div class="menuitem" style="border-top:1px solid #d2dce1; margin-top:20px;">
        <a href="/Management/Home">Home</a>
    </div>
    <div class="menuitem">
        <a href="/Management/Account">Reviews</a>
    </div>
    <div class="menuitem">
        <a href="/Management/MyAccount">My Account</a>
    </div>
    <div class="menuitem">
        <a href="/Management/ChangePassword">Change Password</a>
    </div>
    
    <h2>Coordinator</h2>
    
    <div class="menuitem" style="border-top:1px solid #d2dce1; margin-top:20px;">
        <a href="/Management/Home">Users</a>
    </div>
    <div class="menuitem">
        <a href="/Management/Account">Reviews</a>
    </div>
    <div class="menuitem">
        <a href="/Management/Account">Projects</a>
    </div>
</div>

<?php
echo $content;


$footer = new \PROJ\Tools\Template("Partial/Footer");
echo $footer;
?>