<?php

/*
 * 20 Fields marked with asterisk (*) are required.
 * 25 Username
 * 26 Password
 *    Repeat Password
 * 27 E-Mail
 * 28 First name
 * 29 Surname
 * 30 City
 * 31 Zip code
 * 32 Street
 * 33 Street number
 * 34 Addition
 * 35 Registration code
 * 36 Register
 * 
 */

$toTranslate = array("register","username","password","repeat_password","email","first_name","surname","city","zipcode","street","street_number","addition","registration_code","fields_marked");
$translator = new PROJ\Services\TranslationService();
$translated = $translator->translateAll($toTranslate);

use PROJ\Helper\XssHelper;

$header = new \PROJ\Tools\Template("Partial/Header");
$header->title = $translated["register"];

echo $header;

$bar = new \PROJ\Tools\Template("Partial/TopBar");
echo $bar;
?>

<div id="register_container">
    <form name='register' method='post' enctype="multipart/form-data">
        <img src="/images/register_top.png">
        <div id="register_container_tophalf">
            <?php if ($hasErrors): ?>
                <div class="alert" style="margin-bottom:20px; padding: 5px;">
                    <p><?php echo $error; ?></p>
                </div>
                <div style="clear:both;"></div>
                <?php
            endif;
            ?>
            <div style="width: 282px; margin-right: 70px; float:left;">
                <p><?php echo $translated["username"] ?>: *</p>
                <input name="username" value="<?php echo(isset($_POST['username']) ? XssHelper::sanitizeInput($_POST['username']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required autofocus />
                <p style="margin-top:15px;"><?php echo $translated["password"] ?>: *</p>
                <input name="password" type="password" name="password" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;"><?php echo $translated["repeat_password"] ?>: *</p>
                <input name="passwordagain" type="password" name="password" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;"><?php echo $translated["email"] ?>: *</p>
                <input name="email" value="<?php echo(isset($_POST['email']) ? XssHelper::sanitizeInput($_POST['email']) : ''); ?>" type="email" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;"><?php echo $translated["first_name"] ?>: *</p>
                <input name="firstname" value="<?php echo(isset($_POST['firstname']) ? XssHelper::sanitizeInput($_POST['firstname']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;"><?php echo $translated["surname"] ?>: *</p>
                <input name="surname" value="<?php echo(isset($_POST['surname']) ? XssHelper::sanitizeInput($_POST['surname']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
            </div>
            <div style="width: 282px; float:left;">
                <p><?php echo $translated["city"] ?>: *</p>
                <input name="city" value="<?php echo(isset($_POST['city']) ? XssHelper::sanitizeInput($_POST['city']) : ''); ?>" type="text" style="margin-top: 10px;" required />
                <p style="margin-top:15px;"><?php echo $translated["zipcode"] ?>: *</p>
                <input name="zipcode" value="<?php echo(isset($_POST['zipcode']) ? XssHelper::sanitizeInput($_POST['zipcode']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="6" required />
                <p style="margin-top:15px;"><?php echo $translated["street"] ?>: *</p>
                <input name="street" value="<?php echo(isset($_POST['street']) ? XssHelper::sanitizeInput($_POST['street']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;"><?php echo $translated["street_number"] ?>: *</p>
                <input name="streetnumber" value="<?php echo(isset($_POST['streetnumber']) ? XssHelper::sanitizeInput($_POST['streetnumber']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;"><?php echo $translated["addition"] ?>:</p>
                <input name="addition" value="<?php echo(isset($_POST['addition']) ? XssHelper::sanitizeInput($_POST['addition']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="3" required />
                <p style="margin-top:15px;"><?php echo $translated["registration_code"] ?>: *</p>
                <input name="registrationcode" value="<?php echo(isset($_GET['registrationcode']) ? XssHelper::sanitizeInput($_GET['registrationcode']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="255" required />
            </div>
            <p style="margin-top:25px; font-size:10px; color: #a1a1a1;"><?php echo $translated["fields_marked"] ?></p>
        </div>
        <img src="/images/register_split.png">
        <div id="register_container_bottomhalf">
            <div class="fancy_button" id="register_button" style="left: 335px; top: 160px;">
                <img src="/images/btn_left.png" />
                <p><?php echo $translated["register"] ?></p>
                <img src="/images/btn_right.png" />
            </div>
        </div>
        <img src="/images/register_bottom.png">
    </form>
</div>

<?php
$footer = new \PROJ\Tools\Template("Partial/Footer");
echo $footer;
?>