<?php
use PROJ\Helper\XssHelper;
$header = new \PROJ\Tools\Template("Partial/Header");
$header->title = "Register";

echo $header;

$bar = new \PROJ\Tools\Template("Partial/TopBar");
echo $bar;
?>

<div id="register_container">
    <form name='register' method='post' enctype="multipart/form-data">
        <img src="/images/register_top.png">
        <div id="register_container_tophalf">
            <?php if ($hasErrors): ?>
            <div class="alert" style="margin-bottom:20px; padding: 5px;">
                 <p><?php echo $error; ?></p>
            </div>
            <div style="clear:both;"></div>
            <?php
            endif;
            ?>
            <div style="width: 282px; margin-right: 70px; float:left;">
                <p>Username:</p>
                <input name="username" value="<?php echo(isset($_POST['username']) ? XssHelper::sanitizeInput($_POST['username']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required autofocus />
                <p style="margin-top:15px;">Password:</p>
                <input name="password" type="password" name="password" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;">Password:</p>
                <input name="passwordagain" type="password" name="password" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;">E-Mail:</p>
                <input name="email" value="<?php echo(isset($_POST['email']) ? XssHelper::sanitizeInput($_POST['email']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;">First name:</p>
                <input name="firstname" value="<?php echo(isset($_POST['firstname']) ? XssHelper::sanitizeInput($_POST['firstname']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;">Surname:</p>
                <input name="surname" value="<?php echo(isset($_POST['surname']) ? XssHelper::sanitizeInput($_POST['surname']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
            </div>
            <div style="width: 282px; float:left;">
                <p>City:</p>
                <input name="city" value="<?php echo(isset($_POST['city']) ? XssHelper::sanitizeInput($_POST['city']) : ''); ?>" type="text" style="margin-top: 10px;" required />
                <p style="margin-top:15px;">Zip code:</p>
                <input name="zipcode" value="<?php echo(isset($_POST['zipcode']) ? XssHelper::sanitizeInput($_POST['zipcode']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="6" required />
                <p style="margin-top:15px;">Street:</p>
                <input name="street" value="<?php echo(isset($_POST['street']) ? XssHelper::sanitizeInput($_POST['street']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;">Street number:</p>
                <input name="streetnumber" value="<?php echo(isset($_POST['streetnumber']) ? XssHelper::sanitizeInput($_POST['streetnumber']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="50" required />
                <p style="margin-top:15px;">Addition:</p>
                <input name="addition" value="<?php echo(isset($_POST['addition']) ? XssHelper::sanitizeInput($_POST['addition']) : ''); ?>" type="text" style="margin-top: 10px;" maxlength="3" required />
            </div>
        </div>
        <img src="/images/register_split.png">
        <div id="register_container_bottomhalf">
            <div class="fancy_button" id="register_button" style="left: 335px; top: 160px;">
                <img src="/images/btn_left.png" />
                <p>Register</p>
                <img src="/images/btn_right.png" />
            </div>
        </div>
        <img src="/images/register_bottom.png">
    </form>
</div>

<?php
$footer = new \PROJ\Tools\Template("Partial/Footer");
echo $footer;
?>