<div>
    <h1>Review</h1>
    <div>
        <table border='4px'>
            <tr>
                <th colspan="2">Gemaakte Reviews</th>
            </tr>
            <tr>
                <th>Instelling</th>
                <th>cijfer</th>
            </tr>
            <?php
            $i = 0;
            foreach ($projects as $project) {
                if ($project->getReview() != null) {
                    $i++;
                    ?>
                    <tr>
                        <th><?php echo $project->getInstitute()->getName(); ?></th>
                        <th><?php echo $project->getReview()->getRating(); ?></th>
                        <th><a href='/Review/Edit/ReviewId=<?php echo $project->getReview()->getId(); ?>'>Edit</a></th>
                    </tr>
                    <?php
                }
            }
            if ($i == 0) {
                echo "<tr><th colspan='2'>Geen gemaakte reviews</th></tr>";
            }
            ?>
        </table>
    </div>
    <br />
    <div>
        <table border='4px'>
            <tr>
                <th colspan="2">Openstaande Reviews</th>
            </tr>
            <tr>
                <th>Instelling</th>
                <th>cijfer</th>
            </tr>
<?php
$i = 0;
foreach ($projects as $project) {
    if ($project->getReview() == null) {
        $i++;
        ?>
                    <tr>
                        <th><?php echo $project->getInstitute()->getName(); ?></th>
                        <th><?php echo $project->getReview()->getRating(); ?></th>
                        <th><a href='/Review/Add/ProjectId=<?php echo $project->getId(); ?>'>Add</a></th>
                    </tr>
        <?php
    }
}
if ($i == 0) {
                echo "<tr><th colspan='2'>Geen openstaande reviews</th></tr>";
            }
?>
        </table>
    </div>
</div>
